name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'gradle'
      - name: Make wrapper executable
        run: chmod +x ./gradlew
      - name: Build (no tests)
        run: ./gradlew -S -i assemble
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/*-fabric.jar
      - name: Upload sources jar
        uses: actions/upload-artifact@v4
        with:
          name: sources jar
          path: build/libs/*-fabric-sources.jar
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'gradle'
      - name: Unit tests (JUnit)
        run: ./gradlew test
      - name: Install xvfb for headless MC
        run: sudo apt-get update && sudo apt-get install -y xvfb
#      - name: Run GameTests
#        run: ./gradlew runGameTest || ./gradlew prodClient  # whichever you configure
